# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog-project_development

test:
  <<: *default
  database: blog-project_test

production:
  <<: *default
  database: blog-project_production
  username: rails101
  password: <%= ENV['RAILS101_DATABASE_PASSWORD'] %>
