# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e692b8a3d609f20af9936f4830293fd07d136560b66a5dbea47cfd3d66a4559959515a63a5b08f6224f67f5a5d00cf65be87093566d32df9f742542f6f150da4

test:
  secret_key_base: 824d720fb94d45a4270975291e4716b745af9a234da19a2edd924c71b937586391a72bc4309c4e30f428fcc8b0ff51fe0a849c31d75c1640bc54ece2478a7981

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
